/**
 * 1on1
 * Hassle-free 1on1 questions.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Question } from '../models/Question';
import { HttpFile } from '../http/http';

export class GetCategoryQuestions200Response {
    'questions'?: Array<Question>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "questions",
            "baseName": "questions",
            "type": "Array<Question>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCategoryQuestions200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

